### ISSUE TITLE
option permettant de pointer sur le proxy ADSL

### ISSUE THREAD

**Issue by niederlec** [Inist-CNRS/inist-tools#1]
Usage actuel : mesurer les performance d'export Zip via l'API ISTEX via une connexion ADSL.
Exemple de syntaxe : `inist proxy adsl`

**Comment by ghost** [comment]
Suggestion intéressante. J'en parle avec Stéphane pour mettre ça au kanban du projet et le prioriser.

**Comment by kerphi** [comment]
@niederlec ceci conviendrait ?

inist shell on --adsl
inist curl on --adsl
inist browser on --adsl

l'idée serait d'ajouter --adsl derrière chaque commande spécifique 

on a aussi discuté d'un switch global mais on pense que par rapport aux cas d'usage c'est pas forcement judicieux de switcher globalement tous les services du genre docker, npm etc ...

**Comment by niederlec** [comment]
Why not !
Pour moi ça serait surtout utile pour la ligne de commande (tes 2 premiers exemples)
Dans le navigateur, je passe par une extension
Claude

**Comment by ghost** [comment]
Ajouté dans la 1.5.
