### ISSUE TITLE
.gitconfig: augmenter le credential à 8 heures?

### ISSUE THREAD

**Issue by parmentf** [Inist-CNRS/inist-tools#11]
Quand j'étais sur mon fixe, j'avais fixé le `credential` de git à 8 heures.
Comme ça, j'étais tranquille *grosso modo* pour une journée de travail.

inist-tools le fixe à une heure (*a priori* en écrasant toute autre valeur). Ça va me changer (mais je peux le supporter, et je comprends que sur un portable, c'est plus sûr de ne pas exagérer le temps durant lequel on n'a pas besoin de se ré-authentifier).

Est-il souhaitable de monter cette durée à 8 heures?

**Comment by kerphi** [comment]
Oui je suis pour monter à 8h
Le 1h c'était finalement très arbitraire en attendant des feedback

**Comment by ghost** [comment]
C'est validé ça sera intégré dans la prochaine release.
Je clos l'issue.
