### ISSUE TITLE
Installation impossible si $HOME diffère des cas standards

### ISSUE THREAD

**Issue by nojhamster** [Inist-CNRS/inist-tools#2]
Dans le cas d'une machine ubuntu liée à l'active directory, $HOME peut prendre la forme `/home/ADS.INTRA.INIST.FR/schurter`. Du coup, l'installation échoue en essayant de déplacer des fichiers dans un endroit qui n'existe pas (`/home/$(logname)`).

Quand l'installation échoue, le paquet se retrouve dans un état instable, et il devient très difficile de revenir en arrière. (`apt-get` et `dpkg` ne veulent plus installer/mettre à jour/désinstaller quoi que ce soit tant que le module instable n'est pas réinstallé)

**Comment by kerphi** [comment]
Bug corrigé, à tester avec la dernière release dispo ici:
https://github.com/Inist-CNRS/inist-tools/tree/master/releases
