### ISSUE TITLE
logname: aucun identifiant

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/inist-tools#3]
Après installation sur ubuntu 16.04LTS j'ai une erreur au lancement de ma session et j'ai la même erreur si je souhaite supprimer le package : 

```
sudo dpkg -r inist-tools
(Lecture de la base de données... 273493 fichiers et répertoires déjà installés.)
Suppression de inist-tools (1.2.14) ...
logname: aucun identifiant
dpkg: erreur de traitement du paquet inist-tools (--remove) :
 le sous-processus script post-removal installé a retourné une erreur de sortie d'état 1
Des erreurs ont été rencontrées pendant l'exécution :
 inist-tools
```

**Comment by kerphi** [comment]
Bug "connu" rencontré entre autre sur le poste de Pascale pendant l'ADE ezmaster.
A priori non bloquant, sa résolution est en priorité haute.

**Comment by touv** [comment]
ce bug bloque le registre et l’installation/suppression des paquets .deb
Le problème est lié au gnome-terminal (mais aussi à d'autres). On peut supprimer le paquet via le terminal texte accessible via CTRL-ALT-F1. Théoriquement on devrait pouvoir l'installer de la même manière.

**Comment by ghost** [comment]
Le problème du logname qui ne renvoit rien en terminaux graphiques est un bug connu spécifique à Ubuntu 16.04. Dans la mesure où son usage ne se justifie pas dans le script incriminé, j'ai commenté en attendant un usage futur qui nécessitera un workaround spécifique à cette version d'Ubuntu.
https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/1537645

Edit : ce bug ne toucherait _que_ gnome-terminal sous _cette_ version spécifique d'Ubuntu...

**Comment by ghost** [comment]
La version 1.3 n'utilise plus logname, quelque que soit la plateforme ou la version d'Ubuntu.
À la place, c'est `who am i | awk '{print $1}' | head -1` qui fait le boulot.

**Comment by ghost** [comment]
Ce bug est maintenant corrigé.
