### ISSUE TITLE
plusieurs ExecStart= dans la config docker

### ISSUE THREAD

**Issue by touv** [Inist-CNRS/inist-tools#5]
```
$ cat  /etc/systemd/system/docker.service.d/inist-tools.conf 
# inist-tools
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon $DOCKER_OPTS -H fd://
EnvironmentFile=/etc/default/docker
ExecStart=/usr/bin/docker daemon $DOCKER_OPTS -H fd://
$
```

**Comment by ghost** [comment]
C'est (presque) "normal"

Extrait de https://docs.docker.com/engine/admin/systemd/ : 

To modify the ExecStart configuration, specify an empty configuration followed by a new configuration as follows:

```
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd --bip=172.17.42.1/16
```

Ce qui n'est pas normal c'est deux fois la ligne `ExecStart=/usr/bin/docker daemon $DOCKER_OPTS -H fd://` qui est, àmha, un effet collateral de l'erreur avec « tr » (qui est maintenant corrigée).

**Comment by ghost** [comment]
Ce bug est corrigé dans la version 1.4.0.
